apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
    version: "1.7"
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        version: "1.7"
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:1.7
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
