apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
    version: "1.7"
  ports:
  - name: port1
    protocol: TCP
    port: 9200
    targetPort: 9200
  - name: port2
    protocol: TCP
    port: 9300
    targetPort: 9300
